# Generated by Django 3.2.7 on 2021-12-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_niveles_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niveles',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
