# Generated by Django 3.2.7 on 2021-12-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_niveles_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=30)),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('nivel', models.PositiveIntegerField()),
                ('dni', models.PositiveIntegerField()),
                ('peso', models.FloatField()),
                ('altura', models.FloatField()),
                ('correo', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
    ]
