# Generated by Django 3.2.7 on 2021-12-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrenado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('entrenado', models.BooleanField(default=False)),
            ],
        ),
    ]
